
DROP DATABASE IF EXISTS 5to_mussitedatabase;
CREATE DATABASE 5to_mussitedatabase;
USE 5to_mussitedatabase;

CREATE TABLE Usuario(
    IdUsuario INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(60) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Contrasena VARCHAR(255) NOT NULL,
    perfilUrl VARCHAR(255) NULL DEFAULT NULL,
    bannerUrl VARCHAR(255) NULL DEFAULT NULL
);

CREATE TABLE Instrumento(
    IdInstrumento INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    instrumento VARCHAR(255) NOT NULL
);

CREATE TABLE Partitura(
    IdPartitura INT AUTO_INCREMENT PRIMARY KEY,
    IdUsuario INT UNSIGNED NOT NULL,
    Titulo VARCHAR(255) NOT NULL,
    ImagenUrl VARCHAR(255) NOT NULL,
    PDFUrl VARCHAR(255) NOT NULL,
    Publicacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    Compositor VARCHAR(255),
    CONSTRAINT FK_Partitura_Usuario FOREIGN KEY (IdUsuario) REFERENCES Usuario (IdUsuario)
);